### ISSUE TITLE
Setup new database (MongoDB)

### ISSUE THREAD

**Issue by matthewcawley02** [mazfil/lab-allocator#102]
Setup a MongoDB database, switching from Firebase. Integration in separate issues.

**Comment by alexdboxall** [comment]
I think it would be good to have separate issues for backend and frontend integration, and then this issue can just be the setup of the database itself.

**Comment by matthewcawley02** [comment]
Alright, edited issue to just be about the setup of the database. Will create separate issues for integration now

**Comment by Edward-Nivison** [comment]
I am going to mention that we made this decision because the Firebase reached its daily limit of uploading and downloading from the free firebase server. This is not ideal and that is why we are fast tracking our implementation of the database onto the VM now that we have access to it. This is also because the School of Computing Facility does not want to have to support another database such as Firebase if they have to, So it is beneficial to both parties if we make a local database on the VM hosted locally on ANU Campus.


This is a decision.
#93

**Comment by matthewcawley02** [comment]
MongoDB has been set up on the ANU VM - with this complete, issues #103 and #104 can begin.
