### ISSUE TITLE
Create the Audit Landing Page

### ISSUE THREAD

**Issue by Edward-Nivison** [mazfil/lab-allocator#24]
The Audit landing page should be fairly simple to create, but we need to properly format it (using markdown) in the README.md file. This landing page should include the criteria needed in this.

[Audit Criteria](https://comp.anu.edu.au/TechLauncher/current_students/evaluation/project_audits/)

Just copied from the teams message I sent earlier in the week.

![image](https://github.com/mazfil/lab-allocator/assets/161534957/29858ae6-b5a1-4bc6-9440-25a670ec1baf)

We can get started by creating issues regarding these and completing them before Monday 9:00am in Week 3! Just remember there are already some issues open that can be applicable to these and some that have been closed as well. Make sure to reference anything closed or re-open them if need be!

**Comment by Edward-Nivison** [comment]
Also where are technical reports from? I can't seem to find where it is mentioned to have those? And for another matter, what they are.

**Comment by alexdboxall** [comment]
Sorry I wasn't able to help with writing the landing page before this morning - is it okay if I still make a few minor changes to it now even though it's past 9am? I was going to add a bit to the technical constraints (e.g. about the system needing to be efficient, i.e. not being able to brute force everything) - and also update the project deliverables so that 'backend design' lasts longer than 1 week (e.g. maybe 2 weeks?)

I did also notice the technical reports folder - I'm not sure what needs to go there but I was thinking about writing up a document about how genetic algorithms work and how they could be applied to our problem (and why brute force, etc. won't work) - so maybe I could upload that there?

**Comment by RachelCaoCC** [comment]
> Sorry I wasn't able to help with writing the landing page before this morning - is it okay if I still make a few minor changes to it now even though it's past 9am? I was going to add a bit to the technical constraints (e.g. about the system needing to be efficient, i.e. not being able to brute force everything) - and also update the project deliverables so that 'backend design' lasts longer than 1 week (e.g. maybe 2 weeks?)
> 
> I did also notice the technical reports folder - I'm not sure what needs to go there but I was thinking about writing up a document about how genetic algorithms work and how they could be applied to our problem (and why brute force, etc. won't work) - so maybe I could upload that there?

yes u can update project deliverable because I am not sure what's the detailed plan so it is a draft for now. 
technical report is mentioned in lecture slides and basically hexuan answered the slide questions so maybe u can revise based on slide?

**Comment by Edward-Nivison** [comment]
Created, may come under review later on
