### ISSUE TITLE
Write the crossover function

### ISSUE THREAD

**Issue by alexdboxall** [mazfil/lab-allocator#50]
The crossover function (`Schedule(Schedule a, Schedule b)`) need to be written. This should take two schedules and return a new one that is similar to both of them.

An idea might be to randomly pick a lab from schedule 1, and put it in the same location in the output schedule. Then copy across one from schedule 2, and continue alternating until all labs are copied across, or courses can't be placed (in which case the rest can be placed with `placeLabRandomly`). 

e.g. some pseudocode
```java
Solution crossover(Solution a, Solution b) {
    Solution c = new Solution();
    until c has all classes {
        transfer random lab from `a` to `c`, if its not already in `c`
        transfer random lab from `b` to `c`, if its not already in `c`
        if (room becomes double booked) {
            undo that and try another combination
        }
        if (can't use locations/times from a or b anymore (e.g. due to clashes / double booking) {
            placeLabRandomly
        }
    } 
    return c
}
```

**Comment by Hexuan-Meng** [comment]
I have written the crossover function in the new branch, it will keep removing and copying the lab from two parents schedules alternatively until both of them are empty, and only pasting to the new schedule if the time is free. After this, for any courses that have available seats less than the number of enrollments, it will place the lab randomly until all courses have enough available seats.

It can ensure all courses are in the new schedule and have enough seats for students. The tutor ratio and room size won't be violated since the new schedule uses the `addAllocation(time, course)` method as the only way to add a new allocation to it. This method already has a check for tutor ratio and room size. Since the new schedule get created should be a valid schedule, no additional validation process is needed.

To make the implementation more easily, I added a new subclass `AllocationWithRoomAndTime` which extends the `Allocation` class. It has two additional fields `Room room` and `Time time`, which indicate the room and time of that allocation. By using this new class, a `Schedule` can be converted to a list of `AllocationWithRoomAndTime` without losing the room and time information. The list of `AllocationWithRoomAndTime` will be used for copying a lab from the parent schedule to the new one, which is easy to see if all allocations of the parent schedule are copied over to the new schedule if the time is available.

This new class can be deleted if we have the room and time field in the class `Allocation` itself, and I think it's better to do that way, since we normally know the room and time when we creating a new `Allocation`, and there is no need to have such subclass.

Another thought is to have an `int availableSeats` field in class `Course`. Sometimes we might want to know how many seats are made available for a course. Having this additional field can allow us tracking and accessing the number of available seats anywhere anytime, which can be more convenient.

Any other thoughts and suggestions are welcome.

**Comment by alexdboxall** [comment]
Great work! I'll take a closer look at the code sometime soon. You can probably add the `room` and `time` to `Allocation` itself if you think it's going to be cleaner than having a separate subclass. I probably wouldn't put `int availableSeats` in class `Course` - as the `Course` should just contain static information about a course and not any details about allocations (the number of available seats depends on which rooms the labs are allocated to). Maybe in Schedule you could keep track of the available seats in each Course if you needed to??

And now that the crossover function has been written, the genetic algorithm works! If you uncomment line 54 of `Solver` it will print out the fitness scores - and they are increasing! (meaning the solution is getting better!)

<img width="561" alt="image" src="https://github.com/mazfil/lab-allocator/assets/21270599/922592d5-a832-43cd-9b55-019eba333fcb">

**Comment by alexdboxall** [comment]
I'll close this issue for now - there is still #63 which relates to the crossover.
