### ISSUE TITLE
Adjust when the backend terminates

### ISSUE THREAD

**Issue by alexdboxall** [mazfil/lab-allocator#61]
The backend currently stops iterating after 30 generations. However, there may still be a lot of potential improvements to go after this.

The backend should be adjusted such that it stops iterating when any of the conditions are met:

- It is at least generation 30, and no improvements have been found for the last 20 generations
- 10 minutes have passed since the program was started

**Comment by Hexuan-Meng** [comment]
Here are some thoughts and questions for the backend algorithm.

According to our genetic algorithm, the first generation of the schedules are generated totally randomly, and the crossover function for combining two schedules also involves some randomness. 

The problem is we cannot guarantee all the schedules of each generation can be generated successfully. In the `placeLabRandomly(Random rng, Course course)` method in the `Schedule` class, if we have no free space to place a lab in our schedule, it will throw an exception.

In the cases that we do not have many courses and number of enrolments, that would be fine. However, if the number of courses and enrolments are large, there may be some cases that the schedule cannot be generated successfully due to the randomness. 

For example, let our population size be 10000, if a single schedule cannot be generated properly, our program will be broken. In fact, even if we fail 9999 times, as long as we have a schedule generated successfully, we've found a solution.

I know there will be a limit of the number of courses and enrolments, but I'm not sure if we can always generate 10000 schedules successfully for each generation in that case.

**Comment by alexdboxall** [comment]
Hmm yeah that is an issue that we do need to fix as it could occasionally happen. I'll make a new issue for that - the issue is moreso about deciding when to stop and not how to handle cases where it is impossible to schedule new courses.

**Comment by alexdboxall** [comment]
Old issue from previous semester - a new issue will be created if necessary.
