### ISSUE TITLE
Update to fitness function - parallel classes

### ISSUE THREAD

**Issue by alexdboxall** [mazfil/lab-allocator#87]
As per Belinda's request - we should update the fitness function such that it favors situations where, for large classes, two or more of the same class is running at the same time in different rooms (this helps the school if there is low attendance in some of them, as they can merge/cancel labs without affecting students' choice of times).

**Comment by Hexuan-Meng** [comment]
A method `getPercentParallelClass()` is added to class `Schedule`. It will return the percentage of parallel classes for large classes as a value between 0 and 1000. A class is considered a large class when the total number of enrollments is greater than 200 (can be set to other number if needed).

The rate is calculated by the number of occurrences where a course (student number > 200) has multiple labs starting at the same time divided by the total number of different starting time for all courses (student number > 200).

Since the occurrence of multiple labs starting at the same time for a course is not very often, the fitness value returned by this method will be small.

In addition, the optimization direction of this method is against the `getPercentDupes()` method, which aims to reduce the time duplication of a course. If we modify the `getPercentDupes()` to only count for courses with enrollments <= 200, then the two methods will be independent. I can make the modification if it's considered to be better.

Let me know if you have any other thoughts of suggestions.

**Comment by matthewcawley02** [comment]
Hexuan implemented this feature with the above commit, can close now. I agree that `getPercentDupes` should only count for courses with enrollments <=200, we can implement this later.
